image: docker:latest
services:
  - docker:dind

stages:
  - build

web-build:
  stage: build
  image: node:8-alpine
  script:
    - npm install
    - npm run build:w11k.de
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - linux


arcade-build:
  stage: build
  image: node:8-alpine
  script:
    - npm install
    - npm run build:aracde
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - linux
