image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

web-build:
  stage: build
  image: node:8-alpine
  script:
    - npm install
    - npm run build:w11k.de
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - linux

web-deploy:
  stage: deploy
  image: node:8-alpine
  script:
    - apk update
    - apk add openssh
    - ls -la /dist
    - ssh-add <(echo "hudson_private_ssh_key")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh jenkins@w11k.de rm -rf /srv/www/www.w11k.de-ng-dropping-stones/*
    - scp dist/* jenkins@w11k.de:/srv/www/www.w11k.de-ng-dropping-stones/
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - linux
